spring:
  application:
    name: config-client
  cloud:
    config:
      label: master #指明远程仓库的分支
      profile: dev  # dev开发环境配置文件;test测试环境;pro正式环境
#      uri: http://localhost:8888/  #指明配置服务中心的网址
      discovery:
        enabled: true #从配置中心读取文件
        serviceId: config-server  #配置中心的servieId，即服务名
server:
  port: 8881

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
