spring:
  application:
    name: config-server
  cloud:
    config:
      label: master #配置仓库的分支
      server:
        git:
          uri: https://gitee.com/huaixiameng/springcloud-config.git #配置git仓库地址
          searchPaths: respo #配置仓库路径
          username:     #访问git仓库的用户名 ,Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          password:     #访问git仓库的用户密码
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




